### PR TITLE
Allow supplier users to view their own supplier pages

### PR DESCRIPTION
**Pull request by sarneaud**
This is protected by a feature flag.

### CODE REVIEW

**Comment by matt-sm** [comment]
Perhaps do a rebase from master and use the integrated feature flag functionality that Prakash has enabled

**Comment by prakash87** [comment]
add `SUPPLIERS_VIEW_OWN_PAGE` to `FEATURE_FLAGS` in config and you can check it from views as `flask_featureflags.is_active('SUPPLIERS_VIEW_OWN_PAGE')`

**Comment by sarneaud** [comment]
Okay, I've incorporated the new feature flags setup.

**Comment by matt-sm** [comment]
:+1:

**Pull request merged**
